[build-system]
requires = ["setuptools>=80.9.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = {find = {where = ["."], include = ["kvbiii_plots*"]}}

[project]
name = "kvbiii_plots"
version = "0.3.0"
description = "A collection of plotting functions for data visualization in Python."
readme = "README.md"
authors = [
    { name = "Jakub Kościan", email = "kuba.koscian001@gmail.com" },
]
maintainers = [
    { name = "Jakub Kościan", email = "kuba.koscian001@gmail.com" },
]
keywords = ["data visualization", "plotting", "matplotlib", "seaborn"]
dynamic = ["dependencies"]
requires-python = ">=3.10"
classifiers = [
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13"
]
license = "LicenseRef-Proprietary"

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}

[project.urls]
homepage = "https://github.com/kvbiii/kvbiii-plots"
repository = "https://github.com/kvbiii/kvbiii-plots"

[tool.pylint.main]
py-version = "3.12"

[tool.pylint."messages control"]
disable = [
    "C0103",
    "C0121",
    "C0200",
    "C0301",
    "C0302",
    "C0412",
    "C0413",
    "E1101",
    "R0801",
    "R0904",
    "R0912",
    "R0913",
    "R0914",
    "R0915",
    "R0917",
    "R1705",
    "R1714",
    "R1720",
    "R1721",
    "R1735",
    "W0212",
    "W0404",
    "W0406",
    "W0612",
    "W0621",
    "W1309",
]